
* ¿Qué problema resuelve una criptomoneda cultural?
** ¿Financiación?
**** ¿Crowfunding? 
     Un grupo podría pedir fondos que se mantendrían en un escrow o smar contract, en caso de no lograr la meta los fondos se retornaria a los inversionistas.
     Ej: Ofertar un concierto para x fecha en x zona, los interesados aportan al contrato que tiene condicionales que pueden ser verificados en el código
** ¿Disminuir comisiones de intermediarios?
*** ¿Tu Boleta?
    ¿Se podría evitar la comisión que cobran intermediarios como Tu Boleta por velar por la devolución del dinero en caso que el concierto se cancele?
* ¿Adopción de la cryptoeconomía como intercambio de valor en el sector cultural? 
** ¿Adopción histórica de intangibles?
*** ¿Aplausos?
*** ¿Seguidores?
*** ¿Aceptación?
*** ¿Representatividad?
** ¿Aceptación como forma de pago?
   En el momento en que alguien necesite la criptomoneda y no pueda hacer minería estaría dispuesto a intercambiar Fiat.
** ¿Qué tipo de smartContract se pueden hacer?
** ¿Ejemplos de Ivy?
These contracts demonstrate the following conditions supported by Bitcoin Script:
*** ¿Requiere una firma de una cuenta particular(clave publica)? Requiring a signature corresponding to a prespecified public key (see LockWithPublicKey)
**** ¿Un productor pone los fondos para el pago del sonido, libera los fondos cuando el sonido esta instalado y funcional?
**** ¿Un fan pone los fondos para recibir una mercancia del grupo, libera los fondos cuando recibe la mercancía a satisfacción?
*** ¿Requerir múltiples firmas? Requiring M signatures corresponding to any of N prespecified public keys (see LockWithMultisig)
*** ¿Verificar un hash?Checking that the cryptographic hash of a string or public key is equal to a prespecified hash (see LockWithPublicKeyHash, RevealCollision, RevealPreimage, RevealFixedPoint)
**** ¿Solo quien demuestre la poseción del hash de la versión original de una imagen puede liberar los fondos en una subasta de coleccionistas ?
*** ¿Esperar un tamaño de bloque, o un tiempo de bloque? Waiting until after a specified block height or block time (see LockUntil, TransferWithTimeout
**** ¿Liberar fondos poco a poco para mantener el día a día de un artista, como un mecenas?
*** ¿Esperar determinado tiempo de presencia en el blockchain? Waiting until the contract has been on the blockchain for longer than a specified duration (see LockDelay, EscrowWithDelay), VaultSpend)

* ¿Nombres?
** ¿Cryptural?
* Aprendizajes de Seiche.one
** ¿Se puede establecer una soberanía sobre un activo cultural? ¿de quién son los museos? ¿de quién podrían ser?
** ¿Qué diferencia hay entre una soberanía y una jurisdicción?
** ¿Se puede modelar la topología de un activo cultural?
** ¿Se pueden administrar los procedimientos tecno-legales entre las instituciones?
** ¿Se puede definir "ciudadanía" en terminos de acceso y movilidad?
** ¿Se pueden entonces entender los conflictos de ciudadanía como conflictos sobre la infraestructura que permite esos flujos?
** ¿Podría verse la infraestructura de los programas de becas y estímulos como un sistema de soberanías complejas? 
*** ¿Cómo puede un sistema de registros inmutables (blockchain)  aportar a la forma como accedemos y nos "movilizamos"  en los proyectos culturales?
*** ¿Qué implicaciones tiene para los proyectos culturales un protocolo de intercambio de valor con capacidades de tantas subdivisiones, ej:satoshis?
*** ¿Cómo pueden implementarse contratos "administrados" por código (smart contracts) en el eltramado cultural? 
**** El Contra-Rider 
     Se da el caso de un grupo musical que tiene unos requerimientos técnicos descritos en un rider técnico que se adjunta a la contratación, en algunos casos el artista pide un anticipo condicionado al complimiento del rider, enviar ese anticipo requiere un estado de "confianza" de parte del promotor y varios gastos asociados a la transferencia de fiat, en este caso, poner los fondos en un e-scrow podría liberar los fondos unicamente cuando el artista verifique que se cumple en contrarider.

